name: Deploy SleepWindDown HTML

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Create package folder
      run: |
        mkdir -p deploy_pkg
        cp "SleepWindDown.html" deploy_pkg/

    - name: Zip package
      run: |
        cd deploy_pkg
        zip -r ../sleepwinddown.zip .
        cd ..

    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'sleepdataanylsis'
        package: 'sleepwinddown.zip'
